# typed: false
# frozen_string_literal: true

# Homebrew formula for audit — generated by scripts/gen-formula.ts.
class Audit < Formula
  desc "Cloudflare-style 8-stage AI vulnerability-discovery agent"
  homepage "https://github.com/ali-master/audit"
  version "1.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ali-master/audit/releases/download/v1.5.0/audit-darwin-arm64.tar.gz"
      sha256 "3deb04a7e339ec1abbe865ef633a0ef3a29e5b0896b25b75270e95c452a848c7"
    end
    on_intel do
      url "https://github.com/ali-master/audit/releases/download/v1.5.0/audit-darwin-x64.tar.gz"
      sha256 "c05194848009c6c7be0b1b307fceaa8679e3a2847afd7c94196902b51fc87fbd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ali-master/audit/releases/download/v1.5.0/audit-linux-arm64.tar.gz"
      sha256 "7425bb2c49b50b2904becc62c403cb4878e1cb480e9a87669489004ade77579c"
    end
    on_intel do
      url "https://github.com/ali-master/audit/releases/download/v1.5.0/audit-linux-x64.tar.gz"
      sha256 "0455a7db2f53a20eceffa69b0a70101d8dc09cba4d489fcbd35063d29783a81b"
    end
  end

  def install
    bin.install "audit"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/audit --version")
    system bin/"audit", "doctor"
  end
end
