#!/usr/bin/env bun
/**
 * Snapshot the runtime assets (prompts/, schemas/, config/) into a generated
 * TypeScript module so a `bun build --compile` standalone binary — which has no
 * sibling files on disk — can still read them. The CLI prefers on-disk copies
 * (dev / npm install) and falls back to this embedded map only when they are
 * absent (the Homebrew binary). Run via `bun run embed`; the binary build runs
 * it automatically.
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const OUT = join(ROOT, "src", "generated-assets.ts");

const embedded: Record<string, string> = {};

function add(dir: string, filter: (f: string) => boolean): void {
  for (const f of readdirSync(join(ROOT, dir)).sort()) {
    if (!filter(f)) continue;
    embedded[`${dir}/${f}`] = readFileSync(join(ROOT, dir, f), "utf8");
  }
}

add("prompts", (f) => f.endsWith(".md"));
add("schemas", (f) => f.endsWith(".schema.json"));
add("config", (f) => f.endsWith(".yaml"));

// Sort keys for deterministic output across machines/regenerations.
const sorted: Record<string, string> = {};
for (const k of Object.keys(embedded).sort()) sorted[k] = embedded[k];

const header =
  "// AUTO-GENERATED by scripts/embed-assets.ts — do not edit by hand.\n" +
  "// Snapshots prompts/, schemas/, and config/ so a compiled binary can read\n" +
  "// them when no sibling files exist on disk. Regenerated by `bun run embed`.\n\n";

writeFileSync(
  OUT,
  `${header}export const EMBEDDED: Record<string, string> = ${JSON.stringify(sorted, null, 2)};\n`,
);

console.log(
  `embedded ${Object.keys(embedded).length} asset(s) → src/generated-assets.ts`,
);
