#!/usr/bin/env bun
/**
 * Generate the Homebrew formula from built tarball checksums. Run after
 * `build:binary all` so dist-bin/audit-<target>.tar.gz.sha256 exist.
 *
 *   bun run scripts/gen-formula.ts            # version from package.json
 *   bun run scripts/gen-formula.ts 1.5.0      # explicit version
 *
 * Writes Formula/audit.rb. The release workflow runs this and publishes it.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
const version = (process.argv[2] ?? pkg.version).replace(/^v/, "");
const repo = "ali-master/audit";

function sha(target: string): string {
  const f = join(ROOT, "dist-bin", `audit-${target}.tar.gz.sha256`);
  if (!existsSync(f)) {
    console.warn(`! missing checksum for ${target} — run build:binary:all first`);
    return "REPLACE_ME";
  }
  return readFileSync(f, "utf8").trim().split(/\s+/)[0];
}

const url = (t: string) =>
  `https://github.com/${repo}/releases/download/v${version}/audit-${t}.tar.gz`;

const formula = `# typed: false
# frozen_string_literal: true

# Homebrew formula for audit — generated by scripts/gen-formula.ts.
class Audit < Formula
  desc "Cloudflare-style 8-stage AI vulnerability-discovery agent"
  homepage "https://github.com/${repo}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${url("darwin-arm64")}"
      sha256 "${sha("darwin-arm64")}"
    end
    on_intel do
      url "${url("darwin-x64")}"
      sha256 "${sha("darwin-x64")}"
    end
  end

  on_linux do
    on_arm do
      url "${url("linux-arm64")}"
      sha256 "${sha("linux-arm64")}"
    end
    on_intel do
      url "${url("linux-x64")}"
      sha256 "${sha("linux-x64")}"
    end
  end

  def install
    bin.install "audit"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/audit --version")
    system bin/"audit", "doctor"
  end
end
`;

mkdirSync(join(ROOT, "Formula"), { recursive: true });
writeFileSync(join(ROOT, "Formula", "audit.rb"), formula);
console.log(`wrote Formula/audit.rb (v${version})`);
